pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                // Checkout the code from your Git repository
                git 'https://github.com/Rsowmya26/dev.git'
                
                // Build the Maven project
                bat 'mvn clean package'
            }
            post {
                success {
                    // Trigger downstream pipeline after successful build
                    build job: 'DownstreamPipelineJobName', parameters: [
                        // add parameters if needed
                    ]
                }
            }
        }
        
        stage('Test') {
            steps {
                // Run Maven tests
                bat 'mvn test'
            }
            post {
                success {
                    // Trigger downstream pipeline after successful tests
                    build job: 'AnotherDownstreamPipelineJobName', parameters: [
                        // add parameters if needed
                    ]
                }
            }
        }
    }
}

